fix_seed=${FIX_SEED:-2026}
echo "Running PatchTST with fix_seed=$fix_seed"
model_name=PatchTST
# no official PatchTST script for this dataset; using official multivariate PatchTST long-forecast profile

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id solar_96_96 \
  --model $model_name \
  --data Solar \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 3 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --d_model 128 \
  --n_heads 16 \
  --d_ff 256 \
  --dropout 0.2 \
  --fc_dropout 0.2 \
  --head_dropout 0 \
  --patch_len 16 \
  --stride 8 \
  --train_epochs 60 \
  --patience 5 \
  --lradj TST \
  --pct_start 0.2 \
  --batch_size 32 \
  --learning_rate 0.0001 \
  --itr 1 \
  --fix_seed $fix_seed

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id solar_96_192 \
  --model $model_name \
  --data Solar \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --e_layers 3 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --d_model 128 \
  --n_heads 16 \
  --d_ff 256 \
  --dropout 0.2 \
  --fc_dropout 0.2 \
  --head_dropout 0 \
  --patch_len 16 \
  --stride 8 \
  --train_epochs 60 \
  --patience 5 \
  --lradj TST \
  --pct_start 0.2 \
  --batch_size 32 \
  --learning_rate 0.0001 \
  --itr 1 \
  --fix_seed $fix_seed

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id solar_96_336 \
  --model $model_name \
  --data Solar \
  --features M \
  --seq_len 96 \
  --pred_len 336 \
  --e_layers 3 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --d_model 128 \
  --n_heads 16 \
  --d_ff 256 \
  --dropout 0.2 \
  --fc_dropout 0.2 \
  --head_dropout 0 \
  --patch_len 16 \
  --stride 8 \
  --train_epochs 60 \
  --patience 5 \
  --lradj TST \
  --pct_start 0.2 \
  --batch_size 32 \
  --learning_rate 0.0001 \
  --itr 1 \
  --fix_seed $fix_seed

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id solar_96_720 \
  --model $model_name \
  --data Solar \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --e_layers 3 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --d_model 128 \
  --n_heads 16 \
  --d_ff 256 \
  --dropout 0.2 \
  --fc_dropout 0.2 \
  --head_dropout 0 \
  --patch_len 16 \
  --stride 8 \
  --train_epochs 60 \
  --patience 5 \
  --lradj TST \
  --pct_start 0.2 \
  --batch_size 32 \
  --learning_rate 0.0001 \
  --itr 1 \
  --fix_seed $fix_seed
