fix_seed=${FIX_SEED:-2026}
echo "Running PatchTST with fix_seed=$fix_seed"
model_name=PatchTST
# no official PatchTST script for this dataset; using official multivariate PatchTST long-forecast profile

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS08.npz \
  --model_id PEMS08_96_12 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 12 \
  --e_layers 3 \
  --enc_in 170 \
  --dec_in 170 \
  --c_out 170 \
  --des 'Exp' \
  --d_model 128 \
  --n_heads 16 \
  --d_ff 256 \
  --dropout 0.2 \
  --fc_dropout 0.2 \
  --head_dropout 0 \
  --patch_len 16 \
  --stride 8 \
  --train_epochs 60 \
  --patience 5 \
  --lradj TST \
  --pct_start 0.2 \
  --batch_size 32 \
  --learning_rate 0.0001 \
  --itr 1 \
  --fix_seed $fix_seed

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS08.npz \
  --model_id PEMS08_96_24 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 24 \
  --e_layers 3 \
  --enc_in 170 \
  --dec_in 170 \
  --c_out 170 \
  --des 'Exp' \
  --d_model 128 \
  --n_heads 16 \
  --d_ff 256 \
  --dropout 0.2 \
  --fc_dropout 0.2 \
  --head_dropout 0 \
  --patch_len 16 \
  --stride 8 \
  --train_epochs 60 \
  --patience 5 \
  --lradj TST \
  --pct_start 0.2 \
  --batch_size 32 \
  --learning_rate 0.0001 \
  --itr 1 \
  --fix_seed $fix_seed

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS08.npz \
  --model_id PEMS08_96_48 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 48 \
  --e_layers 3 \
  --enc_in 170 \
  --dec_in 170 \
  --c_out 170 \
  --des 'Exp' \
  --d_model 128 \
  --n_heads 16 \
  --d_ff 256 \
  --dropout 0.2 \
  --fc_dropout 0.2 \
  --head_dropout 0 \
  --patch_len 16 \
  --stride 8 \
  --train_epochs 60 \
  --patience 5 \
  --lradj TST \
  --pct_start 0.2 \
  --batch_size 32 \
  --learning_rate 0.0001 \
  --itr 1 \
  --fix_seed $fix_seed

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS08.npz \
  --model_id PEMS08_96_96 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 3 \
  --enc_in 170 \
  --dec_in 170 \
  --c_out 170 \
  --des 'Exp' \
  --d_model 128 \
  --n_heads 16 \
  --d_ff 256 \
  --dropout 0.2 \
  --fc_dropout 0.2 \
  --head_dropout 0 \
  --patch_len 16 \
  --stride 8 \
  --train_epochs 60 \
  --patience 5 \
  --lradj TST \
  --pct_start 0.2 \
  --batch_size 32 \
  --learning_rate 0.0001 \
  --itr 1 \
  --fix_seed $fix_seed
